name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        environment-file: environment.yml
    - name: Print Environment
      shell: bash -l {0}
      run: pwd && ls && env
    - name: Build
      shell: bash -l {0}
      run: pip install .
    - name: Test
      shell: bash -l {0}
      run: pytest tests

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
    - name: Run pre-commit hooks
      run: |-
        pip install pre-commit \
        && pre-commit run --all
